### ISSUE TITLE
buffer-bearing-insert.stl - end snaps off

### ISSUE THREAD

**Issue by whi-tw** [geoffrey-young/filament-buffer#1]
Hello! This looks amazing - printing the parts now!

I've had the exact same problems as you described - accessing the wheel on the other buffer solutions leads to so much frustration and shouting, my wife wants to yeet the whole thing out the window.

I've got the first buffer set up, but keep having the end of the `buffer-bearing-insert.stl` snapping off, which means the wheel comes off the axle, leading to all sorts of misery. Is this a common problem / is there a solution? I'm thinking of maybe trying replacing the axle with an M5 screw (with a printed spacer, so the wheel fits snugly around it and a washer to avoid this, but wondered if this is something that you / testers ever came across, and if I'm doing something wrong!

**Comment by whi-tw** [comment]
I think I know the problem - mocking something up and will get back to you

**Comment by whi-tw** [comment]
I think I've got a solution.

The existing part looks like this when put together - note the space between `buffer-screen-a` and `buffer-bearing-insert` inside the bearing:
<img width="1214" alt="Original buffer-bearing-insert.stl section view" src="https://user-images.githubusercontent.com/3595020/218101859-206ee9a5-479b-4f93-84bb-b16712c4e895.png">

My solution is to make `buffer-bearing-insert` longer, meaning that it butts up against `buffer-screen-a`, so the two parts clamp down against each other when the M3 screw is tightened:
<img width="1388" alt="New buffer-bearing-insert.stl section view" src="https://user-images.githubusercontent.com/3595020/218102647-94250336-32ab-4721-b5f9-7d704868f9e8.png">


I've modeled this, and the `.stl` and `.step` are available here: [longer-buffer-bearing-insert.zip](https://github.com/geoffrey-young/filament-buffer/files/10707773/longer-buffer-bearing-insert.zip) ([onshape project](https://cad.onshape.com/documents/82f0ecece68e89c47fa1ffab/w/8ff1339605c828d3a5af0040/e/4c220e18b0531cc9d481d5e8?renderMode=0&uiState=63e645d249c24b246258a8d0)).

**Comment by geoffrey-young** [comment]
hi :)

it’s pretty simple to make the bearing insert longer.  in my own setup there is no space, so maybe you have different sized bearings?  can you provide some measurements of the bearings, and maybe some images of the bearing in the wheel?

**Comment by whi-tw** [comment]
It’s a 608ZZ bearing - I’ll send a picture when I’m next by the printer!It looks exactly like the cross section in the image though. I bought the bearings for the ERCF buffers, and thought they’d be the same ones for this - I believe you said it’s the same wheel, just with a hole bored through for loading (amazing idea btw - works super well!)On 22 Feb 2023, at 04:00, Geoffrey Young ***@***.***> wrote:﻿
hi :)
it’s pretty simple to make the bearing insert longer.  in my own setup there is no space, so maybe you have different sized bearings?  can you provide some measurements of the bearings, and maybe some images of the bearing in the wheel?

**Comment by geoffrey-young** [comment]
ok, try the `m5-bearing` branch and [buffer-screen-b-m5.stl](https://github.com/geoffrey-young/filament-buffer/blob/m5-bearing/stl/buffer-screen-b-m5.stl).  I'm not sure how standard m5x12 button head screws are, but if you have any sitting around this setup should be a bit stronger.  let me know how it works out :)

**Comment by whi-tw** [comment]
Sorry it's taken so long to get back to you.

what kind of bearing are you using? I'd assume they are flush with the flat parts of the filament walls like mine are?

I can't see how there could possibly be no space between the bearings, unless your bearings are ~5mm thick? AFAIK 608 bearings are 7mm thick as standard, so surely there must be a gap?

**Comment by geoffrey-young** [comment]
fixed.  thanks!
