### ISSUE TITLE
STEP files

### ISSUE THREAD

**Issue by whi-tw** [geoffrey-young/filament-buffer#2]
Hi, I'm having some issues with one of the screens. I don't suppose you have a STEP file of this project, do you?

**Comment by TravisWilder** [comment]
Hello 
Would be nice to get the STEP. I would like to see if it makes sense to move the IN / OUT from front and back (or top and bottom) both to the side where the handle is - to have IN and OUT on the same side. Handle would need a rework then as well

**Comment by geoffrey-young** [comment]
hi, all.  I use blender so don’t have step files to offer.

on the in/out sides, through quite a bit of experimentation with an early adopter, we determined that the ingress and egress channels functioned best in the current left-to-right orientation.  happy to have folks play around, though :)
