### ISSUE TITLE
Comments on beta wheel

### ISSUE THREAD

**Issue by TypQxQ** [geoffrey-young/filament-buffer#7]
I love the new beta wheel. From what I've tested so far it works much better than the original. I found the direction of filament important, going from outside to inside (the lip). I also made a smal guide on mine and a visualization window.
I had made my buffer much larger but now with the new wheel I think I can go back to original size. I'm attaching some photos. 
Great work!
![image](https://github.com/geoffrey-young/pika-filament-buffer/assets/24956496/59b5a4b3-601b-4412-944f-119fa41baf28)![image](https://github.com/geoffrey-young/pika-filament-buffer/assets/24956496/f6135afb-6fd8-4f8c-9798-290f5a8b3b71)

**Comment by geoffrey-young** [comment]
glad to hear it's working out.  

are you at a booth somewhere?

**Comment by TypQxQ** [comment]
> are you at a booth somewhere?

No. If you refer to the stickers on the printer, it's from old shows I've displayed it on. But the printer is so big I have to remove the door frame to get it out of the room 😄

**Comment by TypQxQ** [comment]
Just an update, it didn't work as well as I hoped. It's better but the filament still tangles. I have reverese engineered the wheel and I'm trying some alternatives. Here's the original wheel in CAD if intrested:
https://github.com/TypQxQ/pika-filament-buffer/tree/main/cad

**Comment by smumriak** [comment]
Unfortunately, neither original wheel nor the beta wheel allow me to use the pika buffer with more than 4 loops. Specifically with ABS filament. Tangles usually 30-40 minutes into print

**Comment by geoffrey-young** [comment]
I'm going to close this out, in favor of continuing discussion on Discord.
